name: Flutter CI
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - name: Flutter setting
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Decode Cert
        id: write_file
        uses: timheuer/base64-to-file@v1
        with:
          fileName: 'NaotikiApps'
          encodedString: ${{ secrets.SIGNING_KEY }}
      - name: "Install and Build  ğŸ”§"
        run: |
          flutter config --enable-web
          flutter config --enable-windows-desktop
          flutter pub get
          flutter build apk
          flutter build windows
          flutter build web
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          ALIAS: ${{ secrets.ALIAS }}
          KEY_PATH: ${{ steps.write_file.outputs.filePath }}
      - name: "Deploy apk ğŸš€"
        uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
      - name: "Deploy windows ğŸš€"
        uses: actions/upload-artifact@v1
        with:
          name: release-exe
          path: build/windows/runner/Release/BallPythonCalc.exe
      - name: "Upload Web ğŸš€"
        uses: actions/upload-artifact@v1
        with:
          name: release-web
          path: build/web/
  deploy-web:
    needs: [ build-and-deploy ] # The second job must depend on the first one to complete before running, and uses ubuntu-latest instead of windows.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.3.1

      - name: Download Artifacts ğŸ”» # The built project is downloaded into the 'site' folder.
        uses: actions/download-artifact@v1
        with:
          name: release-web
      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: "release-web"# ãƒ‡ãƒ—ãƒ­ã‚¤ãƒ¡ãƒ³ãƒˆãƒ•ã‚©ãƒ«ãƒ€ãƒ¼ã¯ã€ã‚¢ãƒ¼ãƒ†ã‚£ãƒ•ã‚¡ã‚¯ãƒˆã®åå‰ã¨ä¸€è‡´ã™ã‚‹å¿…è¦ãŒã‚ã‚Šã¾ã™ã€‚ãƒ—ãƒ­ã‚¸ã‚§ã‚¯ãƒˆã¯ã€Œbuildã€ãƒ•ã‚©ãƒ«ãƒ€ãƒ¼ã«ãƒ“ãƒ«ãƒ‰ã•ã‚Œã¾ã™ãŒã€ã€Œsiteã€ã®ã‚¢ãƒ¼ãƒ†ã‚£ãƒ•ã‚¡ã‚¯ãƒˆåã‚’ã“ã“ã«é…ç½®ã™ã‚‹å¿…è¦ãŒã‚ã‚Šã¾ã™ã€‚

