name: Flutter CI
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2
      - name: Flutter setting
        uses: subosito/flutter-action@v1
        with:
          channel: stable
      - name: Decode Cert
        id: write_file
        uses: timheuer/base64-to-file@v1
        with:
          fileName: 'NaotikiApps'
          encodedString: ${{ secrets.SIGNING_KEY }}
      - name: "Install and Build  ğŸ”§"
        run: |
          flutter config --enable-web
          flutter config --enable-windows-desktop
          flutter pub get
          flutter build apk
          flutter build windows
          flutter build web
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          ALIAS: ${{ secrets.ALIAS }}
          KEY_PATH: ${{ steps.write_file.outputs.filePath }}
      - name: "Deploy apk ğŸš€"
        uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
      - name: "Deploy windows ğŸš€"
        uses: actions/upload-artifact@v1
        with:
          name: release-exe
          path: build/windows/runner/Release/BallPythonCalc.exe
      - name: "Deploy web ğŸš€"
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          BRANCH: gh-pages
          FOLDER: build/web
